const generals = [
    {
        id:1,
        name:"관우",
        type:"무관",
        camp:"촉",
        force:98,
        intel:82,
        skill:"청룡참"
    },
    {
        id:2,
        name:"장비",
        type:"무관",
        camp:"촉",
        force:97,
        intel:48,
        skill:"호통"
    },
    {
        id:3,
        name:"조운",
        type:"무관",
        camp:"촉",
        force:96,
        intel:78,
        skill:"용맹돌격"
    },
    {
        id:4,
        name:"제갈량",
        type:"문관",
        camp:"촉",
        force:30,
        intel:100,
        skill:"팔진도"
    },
    {
        id:5,
        name:"조조",
        type:"문관",
        camp:"위",
        force:82,
        intel:95,
        skill:"간웅"
    },
    {
        id:6,
        name:"여포",
        type:"무관",
        camp:"기타",
        force:100,
        intel:35,
        skill:"귀신무쌍"
    },
    {
        id:7,
        name:"사마의",
        type:"문관",
        camp:"위",
        force:60,
        intel:99,
        skill:"내분"
    },
    {
        id:8,
        name:"주유",
        type:"문관",
        camp:"오",
        force:71,
        intel:97,
        skill:"화공"
    },
    {
        id:9,
        name:"손권",
        type:"문관",
        camp:"오",
        force:70,
        intel:90,
        skill:"지휘"
    },
    {
        id:10,
        name:"감녕",
        type:"무관",
        camp:"오",
        force:92,
        intel:65,
        skill:"기습"
    }
];
